apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: resource-quota
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: dev
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: dev
  labels:
    app: proxy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.7.9
          resources:
            requests:
              memory: 500M
              cpu: 500m
            limits:
              memory: 500M
              cpu: 500m
