apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels: 
    name: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-k8s-go
  labels:
    app: backend
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: k8s-backend-go
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: backend-k8s-go-service
  labels:
    app: backend
  namespace: dev
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

