apiVersion: v1
kind: Pod
metadata: 
  name: ref-env-pod
spec:
  containers:
    - name: ref-env
      image: nginx:alpine
      env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
