apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dev
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-cpu-limit-range-min-max
  namespace: dev
spec:
  limits:
    - max:
        memory: 1Gi
        cpu: 1
      min:
        memory: 100M
        cpu: 100m
      type: Container
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-limit-range-min-max
  namespace: dev
  labels:
    name: limit-range
spec:
  containers:
    - name: nginx-limit-range
      image: nginx:alpine

