apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  labels:
    app: proxy
data:
  nginx: |
    server {
      listen 80;
      server_name localhost;

      location / {
        root /usr/share/nginx/html;
        index index.html index.html;
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-env
  labels:
    app: proxy-env
data:
  db_host: localhost
  db_user: root
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: proxy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
        - name: nginx-container
          image: nginx:alpine
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: nginx-env
                  key: db_host
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: nginx-env
                  key: db_user
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/conf.d/
      volumes:
        - name: config-volume
          configMap:
            name: nginx-configmap
            items:
              - key: nginx
                path: default.conf
