apiVersion: v1
kind: Pod
metadata:
  name: ram-limits
  labels:
    app: proxy
    env: dev
spec:
  containers:
    - name: ram-limit
      image: polinux/stress
      resources:
        limits:
          memory: "200Gi"
        requests:
          memory: "100Gi"
      command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
