apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ejemplo-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: contenedor-ejemplo
            image: imagen-ejemplo
