apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-1
  labels:
    app: proxy
    env: dev
spec:
  containers:
    - name: nginx-pod-1
      image: nginx:alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: python-pod-2
  labels:
    app: backend
    env: dev
spec:
  containers:
    - name: python-pod-1
      image: python:3.6-alpine
      command: ["sh", "-c", "echo 'Backend python' > index.html && python -m http.server 8080"]
    - name: python-pod-2
      image: python:3.6-alpine
      command: ["sh", "-c", "echo 'Backend python' > index.html && python -m http.server 8081"]
