apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume
  labels:
    name: pv-volume
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-volume
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      name: pv-volume
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: pv-volume
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "12345678"
      volumes:
        - name: pv-volume
          persistentVolumeClaim:
            claimName: pvc-volume
