apiVersion: v1
kind: Pod
metadata:
  name: empty-dir-pod
spec:
  containers:
    - name: empty-dir-container
      image: nginx:alpine
      volumeMounts:
        - mountPath: /var/log/nginx
          name: logs-volume
  volumes:
    - name: logs-volume
      emptyDir: {}
