apiVersion: v1
kind: Pod
metadata:
  name: nginx-server-volume-pod
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    volumeMounts:
    - name: nginx-server-volume
      mountPath: /etc/nginx/conf.d
  volumes:
  - name: nginx-server-volume
    hostPath:
      path: /home/eduar/k8s/volumenes/nginx
